---
# Search query, sorts and filters are managed dynamically
query:
  bool:
    filter:
      - term:
          enabled: true
      - term:
          channel: "{{CHANNEL}}"
    must:
      nested:
        path: attributes
        query:
          bool:
            must:
              multi_match:
                query: "{{QUERY}}"
                fields:
                  - attributes.value
                fuzziness: 1
            should:
              rank_feature:
                field: attributes.score
                boost: 100
from: "{{FROM}}"
size: "{{SIZE}}"
sort:
  - "{{SORT_FIELD}}":
      order: "{{SORT_ORDER}}"
      nested:
        path: "{{SORT_NESTED_PATH}}"
        filter:
          term:
            "{{SORT_FILTER_FIELD}}": "{{SORT_FILTER_VALUE}}"
