imports:
    - { resource: "@MonsieurBizSyliusSearchPlugin/Resources/config/config.yaml" }

monsieur_biz_sylius_search:
    files:
        search: '%kernel.project_dir%/vendor/monsieurbiz/sylius-search-plugin/src/Resources/config/elasticsearch/queries/search.yaml'
        instant: '%kernel.project_dir%/vendor/monsieurbiz/sylius-search-plugin/src/Resources/config/elasticsearch/queries/instant.yaml'
        taxon: '%kernel.project_dir%/vendor/monsieurbiz/sylius-search-plugin/src/Resources/config/elasticsearch/queries/taxon.yaml'
    documentable_classes :
        - 'App\Entity\Product\Product'
    grid:
        limits:
            taxon: [9, 18, 27]
            search: [9, 18, 27]
        default_limit:
            taxon: 9
            search: 9
            instant: 10
        sorting:
            taxon: ['name', 'price', 'created_at']
            search: ['name', 'price', 'created_at']
        filters:
            attributes: [] # Put the attributes you want to add in filters
            options: [] # Put the options you want to add in filters
            apply_manually: false # Will refresh the filters depending on applied filters after you apply it manually
twig:
    globals:
        monsieur_biz_sylius_search_grid_config: '@MonsieurBiz\SyliusSearchPlugin\Model\Config\GridConfig'

# Add JS for plugin for Sylius 2.0
#sylius_ui:
#    events:
#        sylius.shop.layout.javascripts:
#            blocks:
#                monsieur_biz_sylius_search_js:
#                    template: "@MonsieurBizSyliusSearchPlugin/js.html.twig"
#                    priority: 0
