services:

  # Default configuration for services in *this* file
  _defaults:
    # Automatically injects dependencies in your services
    autowire: true

    # Automatically registers your services as commands, event subscribers, etc.
    autoconfigure: true

    # Allows optimizing the container by removing unused services; this also means
    # fetching services directly from the container via $container->get() won't work
    public: false

  # Makes classes in src/ available to be used as services;
  # this creates a service per class whose id is the fully-qualified class name
  MonsieurBiz\SyliusSearchPlugin\:
    resource: '../../*'
    exclude: '../../{Entity,Migrations,Tests,Kernel.php}'

  # Controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  MonsieurBiz\SyliusSearchPlugin\Controller\:
    resource: '../../Controller'
    tags: ['controller.service_arguments']

  # Client configuration.
  JoliCode\Elastically\Client:
    arguments:
      $config:
        host: '%env(MONSIEURBIZ_SEARCHPLUGIN_ES_HOST)%'
        port: '%env(MONSIEURBIZ_SEARCHPLUGIN_ES_PORT)%'
        elastically_mappings_directory: '%kernel.project_dir%/vendor/monsieurbiz/sylius-search-plugin/src/Resources/config/elasticsearch'
        elastically_serializer: 'MonsieurBiz\SyliusSearchPlugin\generated\Normalizer\JaneObjectNormalizer'
        elastically_index_class_mapping:
          # @TODO Add it in config
          documents-fr_fr: \MonsieurBiz\SyliusSearchPlugin\Model\Document\Result
          documents-fr: \MonsieurBiz\SyliusSearchPlugin\Model\Document\Result
          documents-en: \MonsieurBiz\SyliusSearchPlugin\Model\Document\Result
          documents-en_us: \MonsieurBiz\SyliusSearchPlugin\Model\Document\Result
        elastically_bulk_size: 100

  # Add JS for instant search
  monsieurbiz_sylius_search.block_event_listener.layout.javascripts:
    class: Sylius\Bundle\UiBundle\Block\BlockEventListener
    arguments:
      - '@@MonsieurBizSyliusSearchPlugin/Instant/instant_javascript.html.twig'
    tags:
      - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.layout.javascripts, method: onBlockEvent }

  # Add form search in header
  monsieurbiz_sylius_search.block_event_listener.layout.header:
    class: Sylius\Bundle\UiBundle\Block\BlockEventListener
    arguments:
      - '@@MonsieurBizSyliusSearchPlugin/Header/form.html.twig'
    tags:
      - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.layout.header, method: onBlockEvent }

  # Event when a product is added / modified / deleted
  monsieurbiz_sylius_search.event_listener.document_listener:
    class: MonsieurBiz\SyliusSearchPlugin\EventListener\DocumentListener
    arguments:
      - '@MonsieurBiz\SyliusSearchPlugin\Model\Document\Index\Indexer'
    tags:
      - { name: kernel.event_listener, event: sylius.product.post_create, method: saveDocument }
      - { name: kernel.event_listener, event: sylius.product.post_update, method: saveDocument }
      - { name: kernel.event_listener, event: sylius.product.pre_delete, method: deleteDocument }

  MonsieurBiz\SyliusSearchPlugin\Provider\SearchRequestProvider:
    arguments:
      $searchPath: '%monsieurbiz_sylius_search.search_file%'
      $instantPath: '%monsieurbiz_sylius_search.instant_file%'
      $taxonPath: '%monsieurbiz_sylius_search.taxon_file%'

  # Provider to retrieve repositories to index
  MonsieurBiz\SyliusSearchPlugin\Provider\DocumentRepositoryProvider:
    arguments:
      $documentableClasses: '%monsieurbiz_sylius_search.documentable_classes%'


  MonsieurBiz\SyliusSearchPlugin\Controller\SearchController:
    arguments:
      $taxonLimits: '%monsieurbiz_sylius_search.taxon_limits%'
      $searchLimits: '%monsieurbiz_sylius_search.search_limits%'
      $taxonDefaultLimit: '%monsieurbiz_sylius_search.taxon_default_limit%'
      $searchDefaultLimit: '%monsieurbiz_sylius_search.search_default_limit%'
      $instantDefaultLimit: '%monsieurbiz_sylius_search.instant_default_limit%'
      $taxonSorting: '%monsieurbiz_sylius_search.taxon_sorting%'
      $searchSorting: '%monsieurbiz_sylius_search.search_sorting%'
